### ISSUE TITLE
Partial warnings for missing files when reading precipitation input files

### ISSUE THREAD

**Issue by juliedemargnehydris** [DassHydro/smash#103]
Precipitation forecasts from SCHAPI for the PIAF deterministic forecasts are named with the following convention:
piaf_france-antilope-15mn_000015_202305010015_202305010000.tif 
for the accumulated precipitation value of 000015 (with the DDHHMM format) (15 minutes in this case)
for the validity date of 202305010015 (with the YYYYmmDDHHMM format) (01/05/2023 00h15 UTC in this case)
and for the forecast start date (T0) of 202305010000 (with the YYYYmmDDHHMM format) (01/05/2023 00h00 UTC in this case)
corresponding to the first forecast horizon of the 15-min precipitation value from 00h00 to 00h15 on 01/05/2023.

To ingest these precipitation forecast files into SMASH to generate PIAF-based flow forecasts, all the PIAF forecasts from a given T0 were saved into individual sub-directories named with the T0 forecast start date.
Therefore, all the 13 PIAF forecast files from T0 = 202305010000 were saved in the following precipitation sub-directory: 
/home/RHAX/DONNEES/PLUIE/SPATIAL/PIAF/PIAF_1kmL93_input_SMASH_2023/2023/05/01/202305010000/

To run SMASH on a loop of T0 forecast dates, the setup was changed for each T0 defined by the start_time_stamp variable (in python format '%Y%m%d%H%M%S'):
path_PIAF = '/home/RHAX/DONNEES/PLUIE/SPATIAL/PIAF/PIAF_1kmL93_input_SMASH_2023/'
year_t0,month_t0,day_t0,hour_t0 = start_time_stamp[0:4],start_time_stamp[4:6],start_time_stamp[6:8],start_time_stamp[8:10]
setup["prcp_directory"] = path_PIAF + (year_t0) + "/" + (month_t0) + "/" + (day_t0) + "/" + start_time_stamp[0:12] + "/"

The flow forecasts are produced for the +12h forecast horizon. Since the PIAF precipitation forecasts are available only on the first +3h15 horizon, SMASH should detect missing precipitation files for the horizon from +3h30 to +12h00.
However, SMASH would give the warnings only for some of the missing precipitation files when running the script on a loop of start dates.

Additional testing was performed to test out the _read_input_data.py function for the function _read_prcp to:
1) print out the value of the list of files that were detected by SMASH : 
for the condition if setup.prcp_format == "tif" and right after the command :  files = _adjust_left_files(files, date_range)

2) print out the value of the ind variable for all the forecast dates
right after the command ind = _index_containing_substring(files, date_strf)
ind = -1 when the precipitation file is missing, otherwise ind = 0

3) print out the filename when reading a tif file when ind=0

The code runs correctly, detecting all the PIAF forecast files up to the +3h15 horizon and all the missing files for the longer horizons, thus assigning the right value to the variable ind.
But the warnings were given for all the dates only when adding the following:
import warnings 
warnings.simplefilter("always")

Therefore the current code runs correctly when using the SCHAPI convention name for the precipitation forecast files if the forecast files are saved in specific sub-directories for each forecast start date T0.
But the warnings when detecting missing precipitation files would not be all printed out by default.
The user needs to include the option to always print out the warnings with the command : warnings.simplefilter("always")

**Comment by inoelloc** [comment]
Issue fix since 1.0 release. See [release note](https://smash.recover.inrae.fr/release/1.0.0-notes.html#reading-of-atmospheric-and-physiograhic-data)
