### ISSUE TITLE
ENH: add the infiltrating rainfall P_s and actual evapotranspiration flux E_s to return_options

### ISSUE THREAD

**Issue by nghi-truyen** [DassHydro/smash#276]
The following two fluxes, which are corrected by the hybrid models, are missing in the return_options:
- infiltrating rainfall P_s
- actual evapotranspiration flux E_s

**Comment by inoelloc** [comment]
@nghi-truyen 
Every fluxes that are not inout of elemental subroutine of each module are not returned. We need to change the signature of this subroutine to handle this.

**Comment by nghi-truyen** [comment]
Yes, for example, we need to change ps and es to intent(out) in the production routine, and then pass them into returns%internal%fluxes in the gr4_time_step routine (and also add make some changes to the Python interface, e.g. _constant.py of course). Does that pose a problem?

**Comment by inoelloc** [comment]
Yes I'd go for this

**Comment by nghi-truyen** [comment]
P.S.: I just merged the writing fluxes code into my branch with hybrid models here:
https://github.com/nghi-truyen/smash-dev/tree/enh-hybrid-models
(I haven't put in a PR for this branch yet because I am waiting for the two previous PRs to be completed, but no pressure at all for you ;))

So I'd rather address this issue after the branch on hybrid models is merged.
