### ISSUE TITLE
ENH/DOC: merge "Imperviousness" and "Horto", make tests and prepare a tutorial on this please.

### ISSUE THREAD

**Issue by pag13** [DassHydro/smash#306]
tuto on Marseille Metropole also with improved soil imperviousness map from Ahmad?

**Comment by pag13** [comment]
Thanks, 
I think Ahmad could finish this investigation on bounds, also a testing on a larger sample...

**Comment by asjeb** [comment]
Il va manquer l'adresse du serveur d'hébergement pour les données de la métropole.
