### ISSUE TITLE
BUG/MAINT: Calculation of pr in production

### ISSUE THREAD

**Issue by nghi-truyen** [DassHydro/smash#336]
Why not write `pr = pn - ps` instead of `pr = pn - (hp_imd - hp) * cp`? Mathematically, the second expression is incorrect because `(hp_imd - hp) * cp = ps - es`, not `ps`.

**Comment by inoelloc** [comment]
La pluie est neutralisée par l'etp avant de rentrer dans la production (voir gr_interception). Donc en entrée de la fonction de production, soit `pn` est positif et `en` nul soit `pn` est nul et `en` positif. Ensuite, dans le calcul de `ps` et `es`, on va avoir `tanh(pn)` ou `tanh(en)` et vu que `tanh(0) = 0`, `es = 0` si `en = 0` et `ps = 0` si `pn = 0`. Au final, si `ps` est positif, `es` est nul et vice versa. L'expression peut porter à confusion, on peut changer ca et mettre `pr = pn - ps`, on devrait avoir les memes résultats plus ou moins la précision machine.

**Comment by nghi-truyen** [comment]
> La pluie est neutralisée par l'etp avant de rentrer dans la production (voir gr_interception). Donc en entrée de la fonction de production, soit `pn` est positif et `en` nul soit `pn` est nul et `en` positif. Ensuite, dans le calcul de `ps` et `es`, on va avoir `tanh(pn)` ou `tanh(en)` et vu que `tanh(0) = 0`, `es = 0` si `en = 0` et `ps = 0` si `pn = 0`. Au final, si `ps` est positif, `es` est nul et vice versa. L'expression peut porter à confusion, on peut changer ca et mettre `pr = pn - ps`, on devrait avoir les memes résultats plus ou moins la précision machine.

Oui oui, je m'en doute, y'aura pas de différence numériquement comme ps et es ne peuvent pas être positifs en même temps (tant mieux pour les runs !!) mais oui il faudra changer l'expression pour rendre ça plus clair. Bon on parlera de tout ça !

**Comment by pag13** [comment]
Oui on a le bon comportement avec l'effet de la routine de neutralisation cpdt c'est l'expression pr = pn - ps qui est à calculer dans gr_production.
